"use client";
import { useEffect, useRef, type ReactNode } from "react";
import { Button } from "./button";
import { Card } from "./surfaces";
function useEscape(open: boolean, onClose: () => void) { useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [onClose, open]); }
export function Modal({ open, title, onClose, children }: Readonly<{ open: boolean; title: string; onClose: () => void; children: ReactNode }>) { useEscape(open, onClose); if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><Card role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-lg animate-[ui-in_.18s_ease-out] p-6"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-bold">{title}</h2><Button variant="ghost" onClick={onClose} aria-label="Закрыть">×</Button></div><div className="mt-5">{children}</div></Card></div>; }
export function Drawer({ open, title, onClose, children }: Readonly<{ open: boolean; title: string; onClose: () => void; children: ReactNode }>) { useEscape(open, onClose); if (!open) return null; return <div className="fixed inset-0 z-50 bg-black/45 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside role="dialog" aria-modal="true" aria-label={title} className="absolute inset-y-0 right-0 w-[min(90vw,28rem)] animate-[drawer-in_.2s_ease-out] bg-[var(--surface)] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><Button variant="ghost" onClick={onClose} aria-label="Закрыть">×</Button></div><div className="mt-5">{children}</div></aside></div>; }
export function ConfirmDialog({ open, title, message, confirmLabel = "Подтвердить", onConfirm, onCancel, danger = false }: Readonly<{ open: boolean; title: string; message: string; confirmLabel?: string; onConfirm: () => void; onCancel: () => void; danger?: boolean }>) { return <Modal open={open} title={title} onClose={onCancel}><p className="text-sm leading-6 text-[var(--text-muted)]">{message}</p><div className="mt-6 flex justify-end gap-3"><Button variant="ghost" onClick={onCancel}>Отмена</Button><Button variant={danger ? "danger" : "primary"} onClick={onConfirm}>{confirmLabel}</Button></div></Modal>; }
export function Dropdown({ trigger, children, label = "Меню" }: Readonly<{ trigger: ReactNode; children: ReactNode; label?: string }>) { const details = useRef<HTMLDetailsElement>(null); return <details ref={details} className="relative"><summary className="list-none cursor-pointer [&::-webkit-details-marker]:hidden">{trigger}</summary><Card role="menu" aria-label={label} className="absolute right-0 z-30 mt-2 min-w-48 animate-[ui-in_.15s_ease-out] p-2">{children}</Card></details>; }
export function Tooltip({ label, children }: Readonly<{ label: string; children: ReactNode }>) { return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 z-40 mb-2 -translate-x-1/2 whitespace-nowrap rounded-lg bg-[var(--text)] px-2.5 py-1.5 text-xs text-[var(--background)] opacity-0 shadow-lg transition group-hover:opacity-100 group-focus-within:opacity-100">{label}</span></span>; }
